# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
            21, # Current Java LTS
          ]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: "microsoft"

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build for all versions
        run: ./gradlew build

      - name: publish on GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        if: github.ref == 'refs/heads/main'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: build for 1.21.3
        run: ./gradlew buildMc1213
        if: github.ref == 'refs/heads/main'

      - uses: Kir-Antipov/mc-publish@v3.3
        if: github.ref == 'refs/heads/main'
        with:
          modrinth-id: PqDbGlPm
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

      - name: build for 1.21.6
        run: ./gradlew buildMc1216
        if: github.ref == 'refs/heads/main'

      - uses: Kir-Antipov/mc-publish@v3.3
        if: github.ref == 'refs/heads/main'
        with:
          modrinth-id: PqDbGlPm
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

      - name: build for 1.21.9
        run: ./gradlew buildMc1219
        if: github.ref == 'refs/heads/main'

      - uses: Kir-Antipov/mc-publish@v3.3
        if: github.ref == 'refs/heads/main'
        with:
          modrinth-id: PqDbGlPm
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
